### ISSUE TITLE
ICD not working

### ISSUE THREAD

**Issue by TomHsiung** [openemr/openemr#2479]
I have installed the openEMR for Linux on my Ubuntu server. I am noob to openEMR but it seems that the ICD searching function did not work. Nothing feedback after searching.

Tom

**Comment by mdsupport** [comment]
Did you load the files via Admin -> Other -> External Data Loads?

**Comment by TomHsiung** [comment]
Not yet. So I must install the external data base by myself? Where to get these external databases? Thank you.

**Comment by mdsupport** [comment]
Install source includes relatively recent data files for various code sets if there are no licensing issues.  In every case there are instructions on where to get the latest files.  See [this wiki page](https://www.open-emr.org/wiki/index.php/Import_Standard_Tables) for more.

**Comment by mdsupport** [comment]
[Demo systems](https://www.open-emr.org/demo/) are great resources to make sure your system is set up correctly.  It resets daily.  I loaded ICD10s in main system.  You can try others to confirm standard process works.  Then go back to your system and find setup issues.  It could be as simple as the directory permissions not in accordance with install instructions.  Then start with running same query manually - assuming /tmp directory still has the extracted file when query failed.

**Comment by TomHsiung** [comment]
I don't know which part is wrong.

**Comment by mdsupport** [comment]
> start with running same query manually - assuming /tmp directory still has the extracted file when query failed

All the best.

**Comment by bradymiller** [comment]
hi @TomHsiung ,

Possible your mysql/mariadb is set to not support LOAD DATA LOCAL INFILE
https://stackoverflow.com/questions/10762239/mysql-enable-load-data-local-infile

Note most default setups of mysql/mariadb supports this, although this seems to be more of an issue on shared hosting

**Comment by TomHsiung** [comment]
> > start with running same query manually - assuming /tmp directory still has the extracted file when query failed
> 
> All the best.

I'm not a coder. I am a pharmacist. Sorry, I know little about computer.

Tom

**Comment by TomHsiung** [comment]
Seems like a issue caused by PHP configuration.

![Screen Shot 2019-06-14 at 3 02 14 PM](https://user-images.githubusercontent.com/6930263/59489689-797d7280-8eb5-11e9-9b8f-1f3f427e40ac.png)

**Comment by bradymiller** [comment]
hi @TomHsiung ,
thanks for the report
-brady

**Comment by bradymiller** [comment]
I just noted this error on docker with php versions 7.2/7.3 but not 7.1. Suspicious that default setting for MYSQLI_OPT_LOCAL_INFILE (https://stackoverflow.com/questions/16739757/load-data-local-infile-command-not-allowed), has been turned off by default in more recent versions of php. Also possible we turned this off while securing dockers. Will look into.

**Comment by bradymiller** [comment]
The demo farm dockers that are using alpine 3.9 and edge also have this issue. So, this appears to be from default configuration of either php or mysql in more recent alpine versions. Will continue researching this.

**Comment by bradymiller** [comment]
Found where the issue stemmed from. https://www.php.net/manual/en/mysqli.configuration.php
```
Name | Default | Changeable | Changelog
mysqli.allow_local_infile | "0" | PHP_INI_SYSTEM | Available as of PHP 5.2.4. Before PHP 7.2.16 and 7.3.3 the default was "1".
```

**Comment by bradymiller** [comment]
fixed and also updated the FAQ to ensure mysqli.allow_local_infile is turned on in php.ini

**Comment by shahawi** [comment]
I will add that as for myself using shared hosting will be extremely difficult since this setting cannot be changed per user,
I suggest people using shared hosting to use php 7.1 maybe?
Haven't tried it yet.

**Comment by stephenwaite** [comment]
hi @shahawi , yeah, will be difficult but should use a [supported version](https://www.php.net/supported-versions.php) of php.

**Comment by shahawi** [comment]
I can confirm that changing php to version 7.1 does not fix the issue as I said before it is a server setting, I am on NixiHost mini shared hosting

**Comment by stephenwaite** [comment]
hi @shahawi, can you ask them to look into it?

**Comment by shahawi** [comment]
The php.ini changes you requested are service-level changes that can only be changed for the entire server, rather than on a "per user" basis. Therefore, it won't be possible to make this change on a shared account as it would affect all sites hosted on the same server.

This is their response

**Comment by shahawi** [comment]
I suggest maybe listing web hosts that support OpenEmr installations on their shared hosting plans

For them it would be a huge advertising opportunity

Or if this setting could be bypassed? I am not a backend developer so I don't really understand how to do that

**Comment by stephenwaite** [comment]
they should be able to provide a custom php.ini for your use like other hosting services

**Comment by shahawi** [comment]
I don't think they can since the php settings are shared at least some settings in it

**Comment by stephenwaite** [comment]
pretty sure there's ways to do it with virtual hosts

**Comment by shahawi** [comment]
https://support.cpanel.net/hc/en-us/articles/360051963873-Why-aren-t-php-ini-changes-working-

**Comment by shahawi** [comment]
Is there a way to know which features are affected by this setting since my installation is seemingly working properly

**Comment by adunsulag** [comment]
@shahawi You should not be using a hosting provider that is using deprecated versions of PHP such as PHP 7.1.  If you have to meet HIPAA and HITRUST security verifications for US requirements then you would be operating in a non-HIPAA compliant environment as your data is at risk of being hacked.  Shared hosting is usually a pretty big no-no for protecting PHI data as well.  You can run on that environment if you want but you may have to hire a private vendor to support and keep secure your data on a deprecated version of PHP.  This will likely be much more expensive than just moving your OpenEMR installation to a better host.

**Comment by shahawi** [comment]
Thank you for your reply 

I live in Egypt 😂

There is no such thing as any requirements for anything

Also as you can imagine budget is a huge factor 

As for the host they support up to php 7.4 but I thought an older version would fix the problem

**Comment by adunsulag** [comment]
@shahawi Unfortunately if your host doesn't let you do the LOAD DATA INFILE you'll have to look at the source code for the importer and try to duplicate the steps through a php script on your own system that can read the CSV and then import the data in batches.  Perhaps someone in the OpenEMR community has already written this process and you can ask on the forums.

**Comment by shahawi** [comment]
Thank you very much for your help

**Comment by sunsetsystems** [comment]
A VPS is cheap these days. For example Digital Ocean has plans from $5/month.

**Comment by shahawi** [comment]
Thank you

I was actually thinking of that it is actually cheaper than my current plan and I can manage my own server
