### ISSUE TITLE
Implement OA2 Authorization server to support:

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#3956]
- ONC 2015+
- Smart on FHIR
- OpenID Connect

Pretty simple justification; ONC requires SOF which requires OpenID Connect which in turn requires OA2 and identity provider.

My plan for phase 1 is to bring in OA2 and create the OIDC authenticate endpoint layer.
From there I hope to next do App registration for those native App developers to start registration development.
Registration is solely up to us how we register public and/or private apps and doesn't necessarily mean it needs to be Smart.
So, OIDC it is or I may allow an OA registration session against legacy password grant type or both. However the days of using our Users simple uname and password are wanning. Apps will be required to register. Re: for single patient/user roles, Apps don't need a registration.

For patient and user roles, registration will be almost automatic.

This project can get rather heady so, any gems of wisdom or contributions, is appreciated.

**Comment by mdsupport** [comment]
Are you planning to include a OA2 server installation as part of emr installation?

**Comment by sjpadgett** [comment]
Hi @mdsupport ,
I am. I decided on using the leagues library as at least it is being maintained. The original author got frustrated with the OA2 committee and walked away in 2017. lol, my kind of guy, a rebel!
The oidc server layer I currently plan to be in the OpenEMR namespace and will be called as an endpoint from the apis directory redirect.

**Comment by sjpadgett** [comment]
Good grief! Trying to follow gov regulatory specs is like trying to track a deer on asphalt!

**Comment by bradymiller** [comment]
especially trying to follow them late at night

![tenor (51)](https://user-images.githubusercontent.com/278968/95179594-b12cbf80-0775-11eb-89d0-070c28ca7a3f.gif)

**Comment by sjpadgett** [comment]
lol, Don't know anymore. I laid down this afternoon for just a minute in my mind and woke up at two a.m!!!

**Comment by sjpadgett** [comment]
Anyone. 
I'm having trouble deciding whether to default to the authorization or implicit grant type. I'm thinking if decide to support for openemr login, authorization is way to go but, for api, perhaps implicit is better choice!

**Comment by bradymiller** [comment]
I vote for explicit (ok, I made that up :) ). From my quick reading, is implicit more for front end stuff?

**Comment by sjpadgett** [comment]
Actually you're right. I got that backwards. Though, i'm now looking at using a Hybrid grant for apis.

**Comment by sjpadgett** [comment]
anyone interested here is what i'm using
https://openid.net/specs/openid-connect-core-1_0.html

**Comment by sjpadgett** [comment]
As I feared, we tied api dispatcher to closely to authentication! Think i'll pull password auth out then just allow dispatcher to deal with tokens and token refresh..

**Comment by bradymiller** [comment]
If I haven't already stated how glad I am that you are doing this and not me, then "I am so glad you are doing this and not me" :)

**Comment by sjpadgett** [comment]
yep Brady and as my family just pointed out to me AGAIN this morning, i'm retired!:) They'll have to pull my keyboard from my cold hands or send it with me if I won't let go even then......!

**Comment by stephenwaite** [comment]
![mp4](https://user-images.githubusercontent.com/5618372/95237448-39db4800-07d6-11eb-93e4-259738a04539.gif)

**Comment by sjpadgett** [comment]
Hmm, wishing won't make it true Stephen:)

**Comment by sjpadgett** [comment]
Come to think of it; I'm not there when i'm on my computer or i'm not there if I go fishing so, can someone please explain to them what the heck is the difference! umm, don't they know me by now! okay enough of that.

Brady I hope to put up a PR later tonight where I hope you'll tackle how we handle auth servers private and public keys..

**Comment by bradymiller** [comment]
whoohooo, more keys and auth work! sadly, that is something I actually look forward to working on :) 
Go argon2, a-r-g-o-n-2
![tenor (53)](https://user-images.githubusercontent.com/278968/95238185-0096de00-07be-11eb-8255-a4f0a8200d10.gif)

**Comment by zerai** [comment]
leauge/OA2 assumes the use of a concrete implementation
  of "psr/http-message" in the request / response cycle management

The codebase should be fixed before introducing OA2 library.

**Comment by sjpadgett** [comment]
@zerai 
Huh! what's psr have to do with auth here?

**Comment by zerai** [comment]
> @zerai
> Huh! what's psr have to do with auth here?

There is no request object or response object in open-emr
we use indiscriminate direct access to php global vars [_POST,_GET,_SESSION]  as request  and a simple string or multi echo statement in  different files as a response.

leauge/OA2 [works](https://github.com/thephpleague/oauth2-server/blob/ffbeb6012bacb70a08b8caca156605c2d7ca7dcc/composer.json#L11) with a request/response object ([example code](https://github.com/thephpleague/oauth2-server/blob/ffbeb6012bacb70a08b8caca156605c2d7ca7dcc/examples/public/api.php#L33).), psr/http-message package define the contract/interfaces for request and response.

[https://www.php-fig.org/psr/psr-7/](https://www.php-fig.org/psr/psr-7/)

**Comment by sjpadgett** [comment]
I still don't understand where we are remiss! Exactly where do we mangle http?
For the oidc/auth server interface i'll be using symfony.

**Comment by zerai** [comment]
My point is you need a considerable refactoring before thinking of OA2 implementation.

**Comment by sjpadgett** [comment]
ugh! oh yeah, multisite!

**Comment by sjpadgett** [comment]
@bradymiller 
Oops, we lost entities directory. I've got to start pulling master more often before developing!!!
How about OpenEMR\RestControllers for AutorizationServer controller and OpenEMR\Common\Auth\OpenIDConnect for repositories and entities(not doctrine entities) namespaces?

**Comment by sjpadgett** [comment]
I'm bored and this is lonely work!

{
  "id_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJvcGVuZW1yZmhpciIsImlzcyI6Imh0dHBzOlwvXC9sb2NhbGhvc3QiLCJpYXQiOjE2MDIzOTEwMTAsImV4cCI6MTYwMjM5NDU5OSwic3ViIjoiMSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0.Kv2pDQTO7luEIMsL-7uNsWZ3BVh-lMHfScUul1rIyFGowmjGOLTwBr6GF1mG957k3eHGg-MPA0jY_v9m0D_7khfRv9aMrat2ArPHOXk7nzsp4PJ0RFCMbNnSkk9idoVniRvo7MnKZVHu0OhFevEI3phynjuKxmaaQ6qhv3sUeppKesOrtb26VOX-Uhnwpp5PZvANdCck7Bt57WIM4Vv7RL101K5vcXwtYZywEDvxfZxI5K3Ndf_NPMw8spAIhc13il21BRQUwGoQuNGXc8CT9Z-VVrN1V4HNyp6tPd7xpugUKzMMXgourrNzvNBCdVMnUfn6YDvwDHvmUNxmiDvkXw",
  "token_type": "Bearer",
  "expires_in": 3600,
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJvcGVuZW1yZmhpciIsImp0aSI6ImE0Mjc3OWIzODc0ZjQ2NGQ4MmZjYTY2ODIwMDY3ZDliMmZmMzI4MDExNTZkYmU5ZmY5YmQzNjJkMzQxYTRlNGJiNDY4MGU3MTNiODRjYTI1IiwiaWF0IjoxNjAyMzkwOTk5LCJuYmYiOjE2MDIzOTA5OTksImV4cCI6MTYwMjM5NDU5OSwic3ViIjoiMSIsInNjb3BlcyI6WyJvcGVuaWQiLCJmaGlyIiwicGFzc3dvcmQiLCJlbWFpbCJdfQ.LCXyAITud5L9Msbb4PmQp3EUgB5ATerAekZsrbjerr4wSYSfYjjCNqDEIlFaYhyQFVLnuTH2LTXIYBWQedVmHKmbZP-fyI8AnxMRPaXjlHR3snbZl8GHq1eohZbrNj8vwfz7yK8zFC7WLAjZlNThkSsubvSgYde-f3OoU1BUtB64pr3KcBWcRrXggV1rfo04cw10E0THd33K_f6Y7cXQx7oOz9a9iApVhURB0_xI3zgmhQJaLv70II-ODUYN1yp4bC4TdOQjLydr8k-_aXblykztb95a8R8j_xukHmUhqmXj1ugfVJf7USsJtUYMfa08e6tC7pw6kyaFYx9lxZPTtA",
  "refresh_token": "def502000721f0e9dbbbde6db8c4e4f9645c03aab2cb17fd37738eb41df0f54ca66b3e93fc10c9195d940fa25b610ff49c7e0f624e13c932427309f6d336817d1fa88cd29fb8ca792bf1d6a3637e4a6c2edf0066cbece8757ee1224969d2ee5317cd459f97667685b4350aceae67c2a19f4d0546659b0697e5d0bc704ada9cc4f5e5dd1b5b6151142cbf743f099baba9122aec446e3f04633e53e93184471361a75425534f6702404ce0f4e5f1ac35dc246e9c0a0625053d4a063f42a101b5d35782e7ffede675835b40025fdac7a3228a3d213b1c24844c4a37ff6463d3f29beb7c6a78ed76e254136f9efa9436904d26866b96a2eacbc40b06c7e60d869299936fa2c75a565066d7f57f7b6e5ce04e773be9a98618363cecea06dcb314c1c7838ad9570fb547ac7da673bf3511752d75a33857541aaa667564603443ebaaa169c35e77a31d965f4f79b0c9f5c096bb2dcdd633f2fba722e0a51d505f28e9866c086a9596800045caaa9fa1492ff4ade408a3f10fdf4d57591b43518982e6434a1b8f9f58506e40e87f310101"
}

Now what do I do with it.:)

**Comment by bradymiller** [comment]
namespaces sounds good to me :)

![tenor (54)](https://user-images.githubusercontent.com/278968/95671238-3551bf00-0b49-11eb-81d8-9ade771ddd8f.gif)

**Comment by sjpadgett** [comment]
@bradymiller Here is a mention for encryption. https://oauth2.thephpleague.com/installation/

**Comment by bradymiller** [comment]
hi @sjpadgett ,

Annoying that the assymetric rsa key has to be a filename (looks like no way to change that), but not end of world. For now would just hard-code one in sites/default/documents/certificates (just stick one there; at some point, will plan to have OpenEMR create random private/public keyset there on the fly when need it).

Regarding the symmetric key, agree that no need to use the OpenEMR's current cryptogen/key classes for this; in this case would create a random 32 byte variable, base64 it, store it in keys mysql table with a oauth label; then just plop this in as the string password (I'll look into incorporating that Defuse Key stuff (considering the Defuse stuff may be going stale, may end up making a class that acts like Defuse Key but isn't :) ) in the future instead of the string password method since sounds like will be faster).

**Comment by sjpadgett** [comment]
> in the future instead of the string password method since sounds like will be faster
thanks Brady,
For our purposes we prob won't see a lot of traffic on either our oauth or oidc identity server where the small speed advantage of not using a password just won't matter much so, do as you see fit imo.
Besides private key storage, I need to find a good endpoint for our well known discovery config. Another multi site delima where it will need to be gen'ed dynamically. Be so much easier if I could terminate the endpoint at the file and make static.

**Comment by mdsupport** [comment]
> I am. I decided on using the leagues library as at least it is being maintained.

Will this server datastore be in emr db thus tying the auth server to a site or interface to a installation specific auth server?

**Comment by sjpadgett** [comment]
> Will this server datastore be in emr db thus tying the auth server to a site or interface to a installation specific auth server?

Yes, supports multisite, db, endpoints and scope will determine site/api request currently.

**Comment by sjpadgett** [comment]
Hi @bradymiller 
taken a few days off and now finally around to dealing with token storage Believe it or not for the access token the library is only using `return \bin2hex(\random_bytes($length=40));`
Now the auth code is RSA so i'm just going to abstract away the bin2hex and use the AuthRestController  method to generate the access token. This way will stay compatible w/legacy and is fine going forward!
Pretty soon:)
![image](https://user-images.githubusercontent.com/1859985/96378659-97b74a80-115b-11eb-948e-a3272f489f4a.png)

**Comment by stephenwaite** [comment]
> anyone interested here is what i'm using
> https://openid.net/specs/openid-connect-core-1_0.html
> 
> this is of interest too
> https://openid.net/specs/openid-connect-registration-1_0.html
> 
> this is to help keep me honest. I am a rebel after all!

if you find anything that you would like to submit as feedback, here's your chance :)
https://www.healthit.gov/isa/svap-standard/170215b

be happy to do that on our behalf

**Comment by sjpadgett** [comment]
Nope @stephenwaite,  @zerai and @matrix-amiel are correct with ONC requirements and how the code flow needs to work. My problem is that i'm more interested with server to server transactions than I am with convenience of the OIDC workflow so when I should be talking about that, my brain is working out the provider client auth flows for import/export/hie's etc. Which is what I wanted to do 2 years ago.
I'm allowed a couple brain farts occasionally because after all, i'm new at this being old stuff. I hear it takes a few years to perfect being old!!!!

**Comment by sjpadgett** [comment]
I stuck on creating a JWK for client JWT validation with the public RS256 key.
My id_token JWT is okay and I can verify against public at jwt.io
This is the summary of my build:

$keyInfo = openssl_pkey_get_details(openssl_pkey_get_public(file_get_contents($loc)));
$jsonData = [
    'keys' => [
        [
            'kty' => 'RSA',
            "use"=> "sig",
            "alg"=> "RS256",
            "kid"=> "1",
            'n' => rtrim(str_replace(['+', '/'], ['-', '_'], base64_encode($keyInfo['rsa']['n'])), '='),
            'e' => rtrim(str_replace(['+', '/'], ['-', '_'], base64_encode($keyInfo['rsa']['e'])), '='),
        ],
    ],
];

**Comment by sjpadgett** [comment]
Does anyone have an oidc client that supports code challenge using the authorization grant type they'd be willing to share with me to use for testing my identity server? 
This is necessary for public applications and to be honest, I'm too lazy to write a client test jig for this.

Also, i'd appreciate any thoughts on how best to register both public and confidential applications for access with OpenEMR.
Should there be a review process etc or should we treat all apps as public and so on....
Note that users still have to sign in to the auth server.

**Comment by mdsupport** [comment]
We use [hybridAuth](https://hybridauth.github.io/).

**Comment by sjpadgett** [comment]
Cool thanks @mdsupport

**Comment by mdsupport** [comment]
> thoughts on how best to register

Would it not be trivial since clients do this all the time? The caller application can be expected to provide something like - I am emr_caller@google.com and here is google.com provided token. If google.com is trusted 3rd party, emr will check with google.com by providing the token and making sure google.com independently returns emr_caller@google.com as one of the attributes.
Here is hybridAuth comment from one of the adapters:
```
/**
* 3. Restore OAuth 1 / OAuth 2 Access Tokens
*
* Instead of calling `Adapter::authenticate()` as we'd normally do, here we simply feed the adapter any stored access tokens
* we have. In case the access tokens we used has been revoked or expired, the provider's will reject the connection, and
* Hybridauth will throw an exception.
*
* Note that these tokens should be the same format and content returned by `Adapter::getAccessToken()`
*/
$adapter->setAccessToken($accessToken);
```

**Comment by sjpadgett** [comment]
Thanks for the input @mdsupport . From my perspective, dealing with the access/id tokens is part of resource server and dispatcher. I have that pretty much worked out. I also have the entire workflow for the authorization grant finished(remember, I am Google in our implementation).
However, as with Google, Amazon or Git etc, the client app/user still needs to register and the best I can tell, only as a private/confidential app/user. This means that the handshake with the provider(Google) uses the client secret issued by provider(on registration) and used by the client for authorization for issue of access/id tokens for the resource server and thus, apis. This is the private app(assumes client can safely store an issued client secret along with client id). Then users client secret is used to authorize an access token.

With a public app/client, a client secret is not issued on registration(assumes client can't safely store the secret). Instead the PKCE code challenge flow is required. This entails the client to send, along with session state, a hashed code(a code challenge) that is used to verify between start and end of auth transaction.

I'm sure many know all this but, while here, this will help me get started on documenting the new feature.

Circling back to registration of apps that will interact with our apis, I've decided on the approach of a dynamic app registration.
We'll honor three app types, web, native and private on registration. Based on the register endpoint from the well known discovery endpoint(domain/siteid/registration) a json encoded post request is sent(example. may be more required):
{
   "application_type": "private",
   "redirect_uris":
     ["https://client.example.org/callback",
      "https://client.example.org/callback2"],
   "client_name": "Private App",
   "token_endpoint_auth_method": "client_secret_post",
   "contacts": ["me@example.org", "them@example.org"]
  }
Resulting in client being registered and client credentials returned(these credentials are mostly needed if client wants to retrieve info later except secret and client id)
{
    "client_id": "dIM5CRrdlEFS-Xepy-EGyE-1tSFMoSiUhBrLlDnfE4k",
    "client_secret": "5rFBHQPBUudXsm79j8nKa-qb1YzgO7R_6DSnof1T8hWV3Ktv31ynfDtjp4608y1xc_wFzE6aD11TeO2mUgYARw",
    "registration_access_token": "klkH-JfYfomLNU8fWmtfDaN3px9RvI5h9DZQNM7u5g0",
    "registration_client_uri": "https:\/\/opensourcedemr.us\/oauth2\/default\/client\/pLyCqj7WnsvR-l0-JCTd1g",
    "client_id_issued_at": 1604243459,
    "client_secret_expires_at": 0,
    "contacts": ["me@example.org", "them@example.org"],
    "application_type": "private",
    "client_name": "Private App",
    "redirect_uris": ["https:\/\/client.example.org\/callback", "https:\/\/client.example.org\/callback2"],
    "token_endpoint_auth_method": "client_secret_post"
}

The big difference with private vs web/native is a client secret would not be issued. However, for a private app, registration will force client to verify their openemr credentials. 
So now client is registered then the user can seek an access token via identity server by hitting the /authorize endpoint where they'd get the normally seen sign in. In our case:
![image](https://user-images.githubusercontent.com/1859985/97806983-4a8faa00-1c2c-11eb-9692-ffcbb7cdd567.png)

![image](https://user-images.githubusercontent.com/1859985/97806962-2af88180-1c2c-11eb-8247-a733e48793d7.png)

Anyway, this is why I was looking for a oidc client that handled both private and public registration and auth flows.

**Comment by sjpadgett** [comment]
Several points.
- if user selects to persist(remember) auth server login consent, instead of issuing cookies i'm going to force a new signin once refresh token expires instead of waiting for user  cookie to expire or be deleted. Some of this is laziness.:)
- decided instead of relying on an offline scope request before a refresh token issuance, will always issue a refresh with TTL of 3 months. Public app support requires additional though.
- For password flow; instead of authorizing via request grant type password hitting the token endpoint, i'm requiring hitting a custom /password endpoint. I don't really want to support the password flow and may simply remove in later release. I'm still not sure on this and may allow via token endpoint too.

@matrix-amiel To answer your question on third party provider support. You'd need to hook out of our providers login dialog by adding a button(along with our login via buttons above) to do the necessary redirect to third party provider then hit the device code endpoint to handle token/client storage and finish openemrs authentication. At least that's my initial thought and much like a social login. In the end, i'll try to help sort that out with you. 
Maybe something like @mdsupport suggested above could work

**Comment by sjpadgett** [comment]
For those interested, I've put up a PR for peer review: https://github.com/openemr/openemr/pull/4013
As soon as I can get some documentation done I plan to merge.
- If you are currently or plan to use our apis, I strongly encourage you to pay attention to this PR as our api base url has to change to support multi site. 
- Also changing is one will have to register their client regardless if using the resource(password) or authorization grant as explained above. Once registered then always registered.
- Mostly OIDC compliant authorization with some unnecessary for openemr items left to do. 
- Password grant can receive a token via hitting the oauth2/default/password or oauth2/default/token endpoint with the password grant type.
- Refresh token is as normal with new access token issued by hitting oauth2/default/token endpoint.

I'll repost on developer forum with an example registration, auth and api session.

The end!
